services:
  db:
    image: mysql:9.0
    restart: always
    container_name: go-ecom-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
